name: gromacs
channels:
  - conda-forge
  - defaults
dependencies:
  - gromacs=2025.4=nompi*
  - matplotlib
  - nglview=3.1.1
  - mdtraj
  - openmm
  - pdbfixer
  - notebook
  - nbconvert
  - numpy
  - requests
  - pandas
  - seaborn
  - compilers
  - openmpi
  - cmake
